export interface Industry {
  id: string;
  name: string;
}

export const idxIndustries: Industry[] = [
  { id: '1', name: 'Minyak' },
  { id: '2', name: 'Gas' },
  { id: '3', name: 'Batubara' },
  { id: '4', name: 'Sumber Energi Lainnya' },
  { id: '5', name: 'Tambang Batu Bara' },
  { id: '6', name: 'Perdagangan Batubara' },
  { id: '7', name: 'Bahan Kimia' },
  { id: '8', name: 'Sumber Daya Mineral' },
  { id: '9', name: 'Baja & Logam' },
  { id: '10', name: 'Kertas & Hasil Hutan' },
  { id: '11', name: 'Konstruksi & Infrastruktur' },
  { id: '12', name: 'Mesin & Alat Berat' },
  { id: '13', name: 'Infrastruktur Transportasi' },
  { id: '14', name: 'Pemasok & Layanan Industri' },
  { id: '15', name: 'Transportasi Udara & Logistik' },
  { id: '16', name: 'Transportasi Laut' },
  { id: '17', name: 'Transportasi Darat' },
  { id: '18', name: 'Layanan Bandara' },
  { id: '19', name: 'Layanan Pelabuhan' },
  { id: '20', name: 'Layanan Bisnis' },
  { id: '21', name: 'Layanan Komersial' },
  { id: '22', name: 'Produk Makanan' },
  { id: '23', name: 'Minuman' },
  { id: '24', name: 'Produk Rumah Tangga' },
  { id: '25', name: 'Produk Perawatan Pribadi' },
  { id: '26', name: 'Perkebunan' },
  { id: '27', name: 'Pakan Ternak' },
  { id: '28', name: 'Perikanan' },
  { id: '29', name: 'Manufaktur Otomotif' },
  { id: '30', name: 'Suku Cadang & Peralatan Otomotif' },
  { id: '31', name: 'Tekstil & Garmen' },
  { id: '32', name: 'Sepatu dan Alas Kaki' },
  { id: '33', name: 'Peralatan Rumah Tangga' },
  { id: '34', name: 'Layanan Konsumen' },
  { id: '35', name: 'Perdagangan Eceran' },
  { id: '36', name: 'Toko Serba Ada' },
  { id: '37', name: 'Ritel Khusus' },
  { id: '38', name: 'Fasilitas Kesehatan' },
  { id: '39', name: 'Obat-obatan' },
  { id: '40', name: 'Peralatan & Perlengkapan Medis' },
  { id: '41', name: 'Layanan Kesehatan' },
  { id: '42', name: 'Bank Umum' },
  { id: '43', name: 'Bank Regional' },
  { id: '44', name: 'Layanan Investasi' },
  { id: '45', name: 'Pembiayaan Konsumen' },
  { id: '46', name: 'Asuransi' },
  { id: '47', name: 'Teknologi Keuangan' },
  { id: '48', name: 'Pengembangan Properti' },
  { id: '49', name: 'Investasi Real Estat' },
  { id: '50', name: 'Manajemen Gedung' },
  { id: '51', name: 'Jasa Konstruksi' },
  { id: '52', name: 'Perangkat Lunak & Layanan' },
  { id: '53', name: 'Perangkat Keras Teknologi' },
  { id: '54', name: 'Semikonduktor' },
  { id: '55', name: 'Layanan Digital' },
  { id: '56', name: 'Utilitas Listrik' },
  { id: '57', name: 'Utilitas Gas' },
  { id: '58', name: 'Utilitas Air' },
  { id: '59', name: 'Telekomunikasi' },
  { id: '60', name: 'Jalan Tol' },
  { id: '61', name: 'Bandara' },
  { id: '62', name: 'Pelabuhan' },
  { id: '63', name: 'Infrastruktur Telekomunikasi' },
  { id: '64', name: 'Media & Hiburan' },
  { id: '65', name: 'Periklanan' },
  { id: '66', name: 'Penyiaran' },
  { id: '67', name: 'Layanan Telekomunikasi' },
  { id: '68', name: 'Peralatan Telekomunikasi' },
];