import { Jabatan } from '../../molecules/core/_models';

const dummyData: Jabatan[] = [
    {
        id: 1,
        name: 'Sales Manager',
        created_at: '29 Januari 2024',
        sales_pengajuan_choose_all: true,
        sales_pengajuan_sales_order: 'View,Create',
        sales_pengajuan_faktur_penjualan: 'View,Delete,Approve',
        sales_pengajuan_pembayaran_penjualan: 'View,Create,Edit,Delete,Approve',
        sales_pengajuan_pergantian_harga: 'View,Create,Edit,Delete,Approve',

        sales_laporan_choose_all: true,
        sales_laporan_sales_order: true,
        sales_laporan_faktur_penjualan: false,
        sales_laporan_pembayaran_penjualan: false,
        sales_laporan_history_harga: false,
        sales_laporan_laporan_transaksi_customer: true,

        sales_masterdata_choose_all: true,
        sales_masterdata_customer: 'View,Create,Edit,Delete',

        purchasing_pengajuan_choose_all: true,
        purchasing_pengajuan_purchase_order: 'View,Create,Edit',
        purchasing_pengajuan_faktur_pembelian: 'View,Create,Edit',
        purchasing_pengajuan_pembayaran_pembelian: 'View,Create,Edit,Delete,Approve',

        purchasing_laporan_choose_all: true,
        purchasing_laporan_purchase_order: true,
        purchasing_laporan_faktur_pembelian: false,
        purchasing_laporan_pembayaran_pembelian: false,
        purchasing_laporan_laporan_transaksi_supplier: false,

        purchasing_masterdata_choose_all: true,
        purchasing_masterdata_supplier: 'View,Create,Edit,Delete',

        pos_choose_all: true,
        pos_aplikasi_pos: 'Access,Manage',
        pos_pos_sales: true,
        pos_shift: 'View,Create,Edit,Delete',
        pos_voucher: 'View,Create,Delete',
        pos_meja: 'View,Create,Edit,Delete',

        inventory_manajemenpengiriman_choose_all: true,
        inventory_manajemenpengiriman_catatan_pengiriman: 'View,Create,Edit,Delete,Approve',
        inventory_manajemenpengiriman_catatan_penerimaan: 'View,Create,Edit,Delete,Approve',
        inventory_manajemenpengiriman_material_request: 'View,Create,Edit,Delete,Approve',
        inventory_manajemenpengiriman_material_transfer: 'View,Create,Edit,Delete,Approve',
        inventory_manajemenpengiriman_retur: 'View,Create,Edit,Delete,Approve',

        inventory_manajemenstock_choose_all: true,
        inventory_manajemenentrystock_entry_stock: 'View,Create,Edit,Delete,Approve',
        inventory_manajemenstockopname_opname_stock: 'View,Create,Edit,Delete,Approve',

        inventory_masterdata_choose_all: true,
        inventory_masterdata_material: 'View,Create,Edit,Delete',
        inventory_masterdata_layanan: 'View,Create,Edit,Delete',
        inventory_masterdata_finish_goods: 'View,Create',
        inventory_masterdata_varian_finis_goods: 'View,Create',
        inventory_masterdata_brand: 'View,Create,Edit,Delete',
        inventory_masterdata_kategori_produk: 'View,Create,Edit,Delete',
        inventory_masterdata_satuan_uom: 'View,Create,Edit',
        inventory_masterdata_item_bundling: 'View,Create,Edit,Delete',

        ppic_choose_all: true,
        ppic_billofmaterial: 'View,Create,Edit,Delete',
        ppic_rencana_produksi: 'View,Create,Edit,Delete,Approve',
        ppic_work_order: 'View,Create,Edit,Delete,Approve',
        ppic_sisa_produksi: 'View,Create,Edit,Delete,Approve',

        accounting_manajementransaksi_choose_all: false,
        accounting_manajementransaksi_entry_transaksi: 'View,Create,Edit,Delete,Approve',
        accounting_manajementransaksi_pengajuan_anggaran: 'View,Create,Edit,Delete,Approve',

        accounting_manajemenaset_choose_all: false,
        accounting_manajemenaset_aset: true,
        accounting_manajemenaset_kategori_aset: true,

        accounting_laporan_choose_all: true,
        accounting_laporan_arus_kas: false,
        accounting_laporan_neraca_keuangan: false,
        accounting_laporan_laporan_laba_rugi: false,
        accounting_laporan_jurnal_umum: false,
        accounting_laporan_buku_besar: false,
        accounting_laporan_rekapitulasi: true,
        accounting_laporan_piutang_usaha: true,
        accounting_laporan_utang_dagang: true,
        accounting_laporan_laporan_penjualan: false,
        accounting_laporan_laporan_pembelian: false,

        hr_dashboard_dashboard_choose_all: false,

        hr_manajemenpegawai_choose_all: false,
        hr_manajemenpegawai_absen: 'View,Create,Edit,Delete,Approve',
        hr_manajemenpegawai_manajemen_lembur: 'View,Create,Edit,Delete,Approve',
        hr_manajemenpegawai_manajemen_cuti: 'View,Create,Edit,Delete,Approve',
        hr_manajemenpegawai_manajemen_perjalanan_dinas: 'View,Create,Edit,Delete,Approve',
        hr_manajemenpegawai_perjalanan_resign: 'View,Create,Edit,Delete,Approve',

        hr_manajemengaji_choose_all: false,
        hr_manajemengaji_slip_gaji: 'View,Create,Edit,Delete,Approve',
        hr_manajemengaji_struktur_gaji: 'View,Create,Edit,Delete,Approve',

        hr_masterdata_choose_all: true,
        hr_masterdata_pegawai: 'View,Create,Edit,Delete',
        hr_masterdata_jabatan: 'View,Create,Edit,Delete',
        hr_masterdata_jenis_cuti: 'View,Create,Edit,Delete',
        hr_masterdata_bagian_slip_gaji: 'View,Create,Edit,Delete',

        company_manajemenperusahaan_manajemen_perusahaan: 'View,Create,Edit,Delete',
    },
    {
        id: 2,
        name: 'Programmer',
        created_at: '30 Januari 2025',
        sales_pengajuan_choose_all: true,
        sales_pengajuan_sales_order: 'View,Create',
        sales_pengajuan_faktur_penjualan: 'View,Delete,Approve',
        sales_pengajuan_pembayaran_penjualan: 'View,Create,Edit,Delete,Approve',
        sales_pengajuan_pergantian_harga: 'View,Create,Edit,Delete,Approve',

        sales_laporan_choose_all: true,
        sales_laporan_sales_order: true,
        sales_laporan_faktur_penjualan: false,
        sales_laporan_pembayaran_penjualan: false,
        sales_laporan_history_harga: false,
        sales_laporan_laporan_transaksi_customer: true,

        sales_masterdata_choose_all: true,
        sales_masterdata_customer: 'View,Create,Edit,Delete',

        purchasing_pengajuan_choose_all: true,
        purchasing_pengajuan_purchase_order: 'View,Create,Edit',
        purchasing_pengajuan_faktur_pembelian: 'View,Create,Edit',
        purchasing_pengajuan_pembayaran_pembelian: 'View,Create,Edit,Delete,Approve',

        purchasing_laporan_choose_all: true,
        purchasing_laporan_purchase_order: true,
        purchasing_laporan_faktur_pembelian: false,
        purchasing_laporan_pembayaran_pembelian: false,
        purchasing_laporan_laporan_transaksi_supplier: false,

        purchasing_masterdata_choose_all: true,
        purchasing_masterdata_supplier: 'View,Create,Edit,Delete',

        pos_choose_all: true,
        pos_aplikasi_pos: 'Access,Manage',
        pos_pos_sales: true,
        pos_shift: 'View,Create,Edit,Delete',
        pos_voucher: 'View,Create,Delete',
        pos_meja: 'View,Create,Edit,Delete',

        inventory_manajemenpengiriman_choose_all: true,
        inventory_manajemenpengiriman_catatan_pengiriman: 'View,Create,Edit,Delete,Approve',
        inventory_manajemenpengiriman_catatan_penerimaan: 'View,Create,Edit,Delete,Approve',
        inventory_manajemenpengiriman_material_request: 'View,Create,Edit,Delete,Approve',
        inventory_manajemenpengiriman_material_transfer: 'View,Create,Edit,Delete,Approve',
        inventory_manajemenpengiriman_retur: 'View,Create,Edit,Delete,Approve',

        inventory_manajemenstock_choose_all: true,
        inventory_manajemenentrystock_entry_stock: 'View,Create,Edit,Delete,Approve',
        inventory_manajemenstockopname_opname_stock: 'View,Create,Edit,Delete,Approve',

        inventory_masterdata_choose_all: true,
        inventory_masterdata_material: 'View,Create,Edit,Delete',
        inventory_masterdata_layanan: 'View,Create,Edit,Delete',
        inventory_masterdata_finish_goods: 'View,Create',
        inventory_masterdata_varian_finis_goods: 'View,Create',
        inventory_masterdata_brand: 'View,Create,Edit,Delete',
        inventory_masterdata_kategori_produk: 'View,Create,Edit,Delete',
        inventory_masterdata_satuan_uom: 'View,Create,Edit',
        inventory_masterdata_item_bundling: 'View,Create,Edit,Delete',

        ppic_choose_all: true,
        ppic_billofmaterial: 'View,Create,Edit,Delete',
        ppic_rencana_produksi: 'View,Create,Edit,Delete,Approve',
        ppic_work_order: 'View,Create,Edit,Delete,Approve',
        ppic_sisa_produksi: 'View,Create,Edit,Delete,Approve',

        accounting_manajementransaksi_choose_all: false,
        accounting_manajementransaksi_entry_transaksi: 'View,Create,Edit,Delete,Approve',
        accounting_manajementransaksi_pengajuan_anggaran: 'View,Create,Edit,Delete,Approve',

        accounting_manajemenaset_choose_all: false,
        accounting_manajemenaset_aset: true,
        accounting_manajemenaset_kategori_aset: true,

        accounting_laporan_choose_all: true,
        accounting_laporan_arus_kas: false,
        accounting_laporan_neraca_keuangan: false,
        accounting_laporan_laporan_laba_rugi: false,
        accounting_laporan_jurnal_umum: false,
        accounting_laporan_buku_besar: false,
        accounting_laporan_rekapitulasi: true,
        accounting_laporan_piutang_usaha: true,
        accounting_laporan_utang_dagang: true,
        accounting_laporan_laporan_penjualan: false,
        accounting_laporan_laporan_pembelian: false,

        hr_dashboard_dashboard_choose_all: false,

        hr_manajemenpegawai_choose_all: false,
        hr_manajemenpegawai_absen: 'View,Create,Edit,Delete,Approve',
        hr_manajemenpegawai_manajemen_lembur: 'View,Create,Edit,Delete,Approve',
        hr_manajemenpegawai_manajemen_cuti: 'View,Create,Edit,Delete,Approve',
        hr_manajemenpegawai_manajemen_perjalanan_dinas: 'View,Create,Edit,Delete,Approve',
        hr_manajemenpegawai_perjalanan_resign: 'View,Create,Edit,Delete,Approve',

        hr_manajemengaji_choose_all: false,
        hr_manajemengaji_slip_gaji: 'View,Create,Edit,Delete,Approve',
        hr_manajemengaji_struktur_gaji: 'View,Create,Edit,Delete,Approve',

        hr_masterdata_choose_all: true,
        hr_masterdata_pegawai: 'View,Create,Edit,Delete',
        hr_masterdata_jabatan: 'View,Create,Edit,Delete',
        hr_masterdata_jenis_cuti: 'View,Create,Edit,Delete',
        hr_masterdata_bagian_slip_gaji: 'View,Create,Edit,Delete',

        company_manajemenperusahaan_manajemen_perusahaan: 'View,Create,Edit,Delete',
    },
    {
        id: 3,
        name: 'CEO',
        created_at: '1 Maret 2022',
        sales_pengajuan_choose_all: true,
        sales_pengajuan_sales_order: 'View,Create',
        sales_pengajuan_faktur_penjualan: 'View,Delete,Approve',
        sales_pengajuan_pembayaran_penjualan: 'View,Create,Edit,Delete,Approve',
        sales_pengajuan_pergantian_harga: 'View,Create,Edit,Delete,Approve',

        sales_laporan_choose_all: true,
        sales_laporan_sales_order: true,
        sales_laporan_faktur_penjualan: false,
        sales_laporan_pembayaran_penjualan: false,
        sales_laporan_history_harga: false,
        sales_laporan_laporan_transaksi_customer: true,

        sales_masterdata_choose_all: true,
        sales_masterdata_customer: 'View,Create,Edit,Delete',

        purchasing_pengajuan_choose_all: true,
        purchasing_pengajuan_purchase_order: 'View,Create,Edit',
        purchasing_pengajuan_faktur_pembelian: 'View,Create,Edit',
        purchasing_pengajuan_pembayaran_pembelian: 'View,Create,Edit,Delete,Approve',

        purchasing_laporan_choose_all: true,
        purchasing_laporan_purchase_order: true,
        purchasing_laporan_faktur_pembelian: false,
        purchasing_laporan_pembayaran_pembelian: false,
        purchasing_laporan_laporan_transaksi_supplier: false,

        purchasing_masterdata_choose_all: true,
        purchasing_masterdata_supplier: 'View,Create,Edit,Delete',

        pos_choose_all: true,
        pos_aplikasi_pos: 'Access,Manage',
        pos_pos_sales: true,
        pos_shift: 'View,Create,Edit,Delete',
        pos_voucher: 'View,Create,Delete',
        pos_meja: 'View,Create,Edit,Delete',

        inventory_manajemenpengiriman_choose_all: true,
        inventory_manajemenpengiriman_catatan_pengiriman: 'View,Create,Edit,Delete,Approve',
        inventory_manajemenpengiriman_catatan_penerimaan: 'View,Create,Edit,Delete,Approve',
        inventory_manajemenpengiriman_material_request: 'View,Create,Edit,Delete,Approve',
        inventory_manajemenpengiriman_material_transfer: 'View,Create,Edit,Delete,Approve',
        inventory_manajemenpengiriman_retur: 'View,Create,Edit,Delete,Approve',

        inventory_manajemenstock_choose_all: true,
        inventory_manajemenentrystock_entry_stock: 'View,Create,Edit,Delete,Approve',
        inventory_manajemenstockopname_opname_stock: 'View,Create,Edit,Delete,Approve',

        inventory_masterdata_choose_all: true,
        inventory_masterdata_material: 'View,Create,Edit,Delete',
        inventory_masterdata_layanan: 'View,Create,Edit,Delete',
        inventory_masterdata_finish_goods: 'View,Create',
        inventory_masterdata_varian_finis_goods: 'View,Create',
        inventory_masterdata_brand: 'View,Create,Edit,Delete',
        inventory_masterdata_kategori_produk: 'View,Create,Edit,Delete',
        inventory_masterdata_satuan_uom: 'View,Create,Edit',
        inventory_masterdata_item_bundling: 'View,Create,Edit,Delete',

        ppic_choose_all: true,
        ppic_billofmaterial: 'View,Create,Edit,Delete',
        ppic_rencana_produksi: 'View,Create,Edit,Delete,Approve',
        ppic_work_order: 'View,Create,Edit,Delete,Approve',
        ppic_sisa_produksi: 'View,Create,Edit,Delete,Approve',

        accounting_manajementransaksi_choose_all: false,
        accounting_manajementransaksi_entry_transaksi: 'View,Create,Edit,Delete,Approve',
        accounting_manajementransaksi_pengajuan_anggaran: 'View,Create,Edit,Delete,Approve',

        accounting_manajemenaset_choose_all: false,
        accounting_manajemenaset_aset: true,
        accounting_manajemenaset_kategori_aset: true,

        accounting_laporan_choose_all: true,
        accounting_laporan_arus_kas: false,
        accounting_laporan_neraca_keuangan: false,
        accounting_laporan_laporan_laba_rugi: false,
        accounting_laporan_jurnal_umum: false,
        accounting_laporan_buku_besar: false,
        accounting_laporan_rekapitulasi: true,
        accounting_laporan_piutang_usaha: true,
        accounting_laporan_utang_dagang: true,
        accounting_laporan_laporan_penjualan: false,
        accounting_laporan_laporan_pembelian: false,

        hr_dashboard_dashboard_choose_all: false,

        hr_manajemenpegawai_choose_all: false,
        hr_manajemenpegawai_absen: 'View,Create,Edit,Delete,Approve',
        hr_manajemenpegawai_manajemen_lembur: 'View,Create,Edit,Delete,Approve',
        hr_manajemenpegawai_manajemen_cuti: 'View,Create,Edit,Delete,Approve',
        hr_manajemenpegawai_manajemen_perjalanan_dinas: 'View,Create,Edit,Delete,Approve',
        hr_manajemenpegawai_perjalanan_resign: 'View,Create,Edit,Delete,Approve',

        hr_manajemengaji_choose_all: false,
        hr_manajemengaji_slip_gaji: 'View,Create,Edit,Delete,Approve',
        hr_manajemengaji_struktur_gaji: 'View,Create,Edit,Delete,Approve',

        hr_masterdata_choose_all: true,
        hr_masterdata_pegawai: 'View,Create,Edit,Delete',
        hr_masterdata_jabatan: 'View,Create,Edit,Delete',
        hr_masterdata_jenis_cuti: 'View,Create,Edit,Delete',
        hr_masterdata_bagian_slip_gaji: 'View,Create,Edit,Delete',

        company_manajemenperusahaan_manajemen_perusahaan: 'View,Create,Edit,Delete',
    },
];

export { dummyData };